services:
  # PostgreSQL Database - Production
  postgres:
    image: postgres:15-alpine
    container_name: ${PROJECT_NAME}-postgres-prod
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      # 성능 최적화
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    ports:
      # 프로덕션에서는 외부 노출 최소화 (필요시 주석 해제)
      # - "${POSTGRES_PORT}:5432"
      - "127.0.0.1:${POSTGRES_PORT}:5432"
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
      # 백업 디렉토리
      - ./backups/postgres:/backups
    networks:
      - nara-network-prod
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    # 리소스 제한
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Redis Cache - Production
  redis:
    image: redis:7-alpine
    container_name: ${PROJECT_NAME}-redis-prod
    command: >
      redis-server
      --appendonly yes
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
      --save 900 1
      --save 300 10
      --save 60 10000
    ports:
      # 프로덕션에서는 외부 노출 최소화
      - "127.0.0.1:${REDIS_PORT}:6379"
    volumes:
      - redis_prod_data:/data
      # Redis 설정 파일 (옵션)
      # - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    networks:
      - nara-network-prod
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # FastAPI Backend - Production
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    container_name: ${PROJECT_NAME}-backend-prod
    environment:
      # Mode & Project Info
      MODE: ${MODE}
      PROJECT_NAME: ${PROJECT_NAME}
      APP_TITLE: ${APP_TITLE}
      APP_DESCRIPTION: ${APP_DESCRIPTION}
      APP_VERSION: ${APP_VERSION}
      # PostgreSQL Database
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      # Redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      # App settings
      APP_ENV: ${APP_ENV}
      DEBUG: ${DEBUG}
      LOG_LEVEL: ${LOG_LEVEL}
      SECRET_KEY: ${SECRET_KEY}
      # API & Auth
      API_V1_STR: ${API_V1_STR}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      FIRST_SUPERUSER: ${FIRST_SUPERUSER}
      FIRST_SUPERUSER_PASSWORD: ${FIRST_SUPERUSER_PASSWORD}
      # CORS
      CORS_ORIGINS: ${CORS_ORIGINS}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      # Workers
      WORKERS: ${WORKERS}
    ports:
      - "${BACKEND_PORT}:8000"
    volumes:
      # .env 파일 마운트
      - ./.env:/app/.env:ro
      # 로그만 마운트
      - ./logs/backend:/app/logs
      - backend_prod_data:/app/data
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - nara-network-prod
    command: gunicorn app.main:app --workers ${WORKERS} --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --timeout ${TIMEOUT} --keep-alive ${KEEP_ALIVE} --log-level ${LOG_LEVEL} --access-logfile - --error-logfile -
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 512M
      replicas: 1
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  # React Frontend - Production
  frontend:
    build:
      context: ./frontend/app
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: ${PROJECT_NAME}-frontend-prod
    environment:
      - NODE_ENV=${NODE_ENV}
    ports:
      - "${FRONTEND_PORT}:80"
      - "${FRONTEND_SSL_PORT}:443"
    volumes:
      # Nginx 로그
      - ./logs/nginx:/var/log/nginx
      # SSL 인증서 (Let's Encrypt 등)
      # - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
    networks:
      - nara-network-prod
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 128M
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    profiles:
      - frontend

  # Nginx Reverse Proxy (옵션 - SSL 종료 및 로드 밸런싱)
  nginx-proxy:
    image: nginx:alpine
    container_name: ${PROJECT_NAME}-nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./logs/nginx-proxy:/var/log/nginx
    depends_on:
      - frontend
      - backend
    networks:
      - nara-network-prod
    restart: unless-stopped
    profiles:
      - proxy
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  # 백업 서비스 (Cron 기반)
  backup:
    image: postgres:15-alpine
    container_name: ${PROJECT_NAME}-backup
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./backups:/backups
      - ./scripts/backup.sh:/backup.sh:ro
    networks:
      - nara-network-prod
    depends_on:
      - postgres
    entrypoint: /bin/sh
    command: -c "crond -f -l 2"
    restart: unless-stopped
    profiles:
      - backup
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  nara-network-prod:
    driver: bridge
    name: ${PROJECT_NAME}-network-prod
    # TODO: 정상동작시 삭제
    # ipam:
    #   config:
    #     - subnet: 172.25.0.0/16

volumes:
  postgres_prod_data:
    driver: local
  redis_prod_data:
    driver: local
  backend_prod_data:
    driver: local
